### PR TITLE
Fix: Populate MaxEnd to parent nodes.

### PR DESCRIPTION
**Pull request by danm-de**
- The property IntervalNode<T>.MaxEnd hasn't been populated to the
  parent nodes.
- Added nuget support
- Added (nunit) test project to reproduce the error and verify the fix.

### CODE REVIEW

**Comment by vvondra** [comment]
Thanks for the fix and the tests.

Is it necessary to commit the Nuget executable in .nuget?

**Comment by danm-de** [comment]
Hi,

works for me if I delete the .nuget directory in the VS solution. Without the nuget-target file you must enable "Automatic download of missing packages" in Visual Studio options. 

I am not sure whether msbuild/xbuild will work without nuget.

**Comment by vvondra** [comment]
I think that's OK. If you could just omit the executable, it'd be good to go. Thanks!  

-----Original Message-----

**Comment by Bomret** [comment]
Please merge this. We really need this fix, pretty please?

**Comment by maximilian-krauss** [comment]
Would love to see this too :+1:

**Comment by vvondra** [comment]
thanks for the ping :)

**Pull request merged**
